version: '3.9'

services:
  nginx:
    container_name: ${CONTAINER_PREFIX:-lamp}-nginx
    image: nginx:1.25-bullseye
    ports:
      - '${NGINX_PORT:-80}:80'
    volumes:
      - projects:/var/www/html
      - ${NGINX_DIR:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_DIR:-./nginx}/default.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_DIR:-./nginx}/sites-enabled:/etc/nginx/sites-enabled
      - ${NGINX_DIR:-./nginx}/php:/etc/nginx/php
      - ${LOGGING_DIR:-./logs}/nginx:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php-74-fpm
      - php-82-fpm
    restart: unless-stopped
  
  php-74-fpm:
    container_name: ${CONTAINER_PREFIX:-lamp}-php7.4
    build: ./php/7.4
    volumes:
      - projects:/var/www/html
      - composer74:/home/${USER_NAME:-dev}/.composer
      - ./ssh:/home/dev/.ssh
    restart: unless-stopped
  
  php-82-fpm:
    container_name: ${CONTAINER_PREFIX:-lamp}-php8.2
    build: 
      context: ./php/8.2
      args:
        USER_NAME: ${USER_NAME:-dev}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        GIT_EMAIL: ${GIT_EMAIL:-''}
        GIT_NAME: ${GIT_NAME:-''}
        NODE_VERSION: ${NODE_VERSION:-14.21.3}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2.6.5}
    volumes:
      - projects:/var/www/html
      - composer82:/home/${USER_NAME:-dev}/.composer
      - ./ssh:/home/dev/.ssh
      - ./php/aliases:/home/${USER_NAME:-dev}/.bash_aliases
      - ./php/scripts:/home/${USER_NAME:-dev}/scripts
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ${HEROKU_SESSION:-./php/_netrc}:/home/${USER_NAME:-dev}/.netrc
    restart: unless-stopped

  mysql:
    container_name: ${CONTAINER_PREFIX:-lamp}-mysql
    image: mysql:8.0-debian
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ${LOGGING_DIR:-./logs}/mysql:/var/log/mysql
      - ${MYSQL_CONF_DIR:-./mysql-conf}:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    container_name: ${CONTAINER_PREFIX:-lamp}-redis
    image: redis:7.2.3-alpine3.18
    ports: 
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  projects:
  mysql:
  redis:
  composer74:
  composer82: