version: '3.9'

x-php-service: &php-service
  build: &php-service-args
    args:
        # For the container's non-root user account
        USER_NAME: ${USER_NAME:-dev}
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
        # Set for streamlining Git CLI use
        GIT_EMAIL: ${GIT_EMAIL:-''}
        GIT_NAME: ${GIT_NAME:-''}
        # Node is installed via NVM so this can be flexible during use
        NODE_VERSION: ${NODE_VERSION:-14.21.3}
        COMPOSER_VERSION: ${COMPOSER_VERSION:-2.6.5}
  volumes:
    # Project files & Composer cache (optional)
    - projects:/var/www/html
    - composer:/home/${USER_NAME:-dev}/.composer
    # PHP config and bashrc aliases & scripts
    - ./php/php.ini:/usr/local/etc/php/php.ini
    - ./php/aliases:/home/${USER_NAME:-dev}/.bash_aliases
    - ./php/scripts:/home/${USER_NAME:-dev}/scripts
    # Passing/storing SSH & Heroku CLI sessions from host
    - ./ssh:/home/dev/.ssh
    - ${HEROKU_SESSION:-./php/_netrc}:/home/${USER_NAME:-dev}/.netrc
  restart: unless-stopped

services:
  php-74-fpm:
    <<: *php-service
    container_name: ${CONTAINER_PREFIX:-lamp}-php7.4
    build:
      <<: *php-service-args
      context: ./php/7.4
  
  php-82-fpm:
    <<: *php-service
    container_name: ${CONTAINER_PREFIX:-lamp}-php8.2
    build:
      <<: *php-service-args
      context: ./php/8.2

  nginx:
    container_name: ${CONTAINER_PREFIX:-lamp}-nginx
    image: nginx:1.25-bullseye
    ports:
      - '${NGINX_PORT:-80}:80'
      - '${NGINX_SSL_PORT:-443}:443'
    volumes:
      - projects:/var/www/html
      - ${NGINX_DIR:-./nginx}/nginx.conf:/etc/nginx/nginx.conf
      - ${NGINX_DIR:-./nginx}/default.conf:/etc/nginx/conf.d/default.conf
      - ${NGINX_DIR:-./nginx}/sites-enabled:/etc/nginx/sites-enabled
      - ${NGINX_DIR:-./nginx}/php:/etc/nginx/php
      - ${NGINX_DIR:-./nginx}/additional/:/etc/nginx/additional/
      - ${LOGGING_DIR:-./logs}/nginx:/var/log/nginx/
      - /etc/localtime:/etc/localtime:ro
    depends_on:
      - php-74-fpm
      - php-82-fpm
    restart: unless-stopped

  mysql:
    container_name: ${CONTAINER_PREFIX:-lamp}-mysql
    image: mysql:8.0-debian
    ports:
      - '${MYSQL_PORT:-3306}:3306'
    volumes:
      - mysql:/var/lib/mysql
      - ${LOGGING_DIR:-./logs}/mysql:/var/log/mysql
      - ${MYSQL_CONF_DIR:-./mysql-conf}:/etc/mysql/conf.d
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_CHARSET=utf8mb4
      - MYSQL_COLLATION=utf8mb4_unicode_ci
    restart: unless-stopped

  redis:
    container_name: ${CONTAINER_PREFIX:-lamp}-redis
    image: redis:7.2.3-alpine3.18
    ports: 
      - '${REDIS_PORT:-6379}:6379'
    volumes:
      - redis:/data
    restart: unless-stopped

volumes:
  projects:
  mysql:
  redis:
  composer:
